// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Timlog.Infrastructure.Data;

#nullable disable

namespace Timlog.Infrastructure.Migrations
{
    [DbContext(typeof(TimlogDbContext))]
    partial class TimlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Timlog.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AadeMark")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClientAfm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<long>("InvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerAfm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("QrUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPayable")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WithholdingAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AadeMark")
                        .IsUnique();

                    b.HasIndex("ClientAfm");

                    b.HasIndex("IssueDate");

                    b.HasIndex("IssuerAfm");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Timlog.Domain.Entities.TenantCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedAadeUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSubscriptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssuerAfm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssuerAfm");

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.ToTable("TenantCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
