//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen InvoicesDoc-v2.0.1.xsd -n http://www.aade.gr/myDATA/invoice/v1.0=Timlog.Infrastructure.Aade.Models
namespace Gr.Aade.MyData.ExpensesClassificaton.V1._0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CountryType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("CountryType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum CountryType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("AD")]
        Ad,
        
        [System.Xml.Serialization.XmlEnumAttribute("AE")]
        Ae,
        
        [System.Xml.Serialization.XmlEnumAttribute("AF")]
        Af,
        
        [System.Xml.Serialization.XmlEnumAttribute("AG")]
        Ag,
        
        [System.Xml.Serialization.XmlEnumAttribute("AI")]
        Ai,
        
        [System.Xml.Serialization.XmlEnumAttribute("AL")]
        Al,
        
        [System.Xml.Serialization.XmlEnumAttribute("AM")]
        Am,
        
        [System.Xml.Serialization.XmlEnumAttribute("AN")]
        An,
        
        [System.Xml.Serialization.XmlEnumAttribute("AO")]
        Ao,
        
        [System.Xml.Serialization.XmlEnumAttribute("AQ")]
        Aq,
        
        [System.Xml.Serialization.XmlEnumAttribute("AR")]
        Ar,
        
        [System.Xml.Serialization.XmlEnumAttribute("AS")]
        As,
        
        [System.Xml.Serialization.XmlEnumAttribute("AT")]
        At,
        
        [System.Xml.Serialization.XmlEnumAttribute("AU")]
        Au,
        
        [System.Xml.Serialization.XmlEnumAttribute("AW")]
        Aw,
        
        [System.Xml.Serialization.XmlEnumAttribute("AX")]
        Ax,
        
        [System.Xml.Serialization.XmlEnumAttribute("AZ")]
        Az,
        
        [System.Xml.Serialization.XmlEnumAttribute("BA")]
        Ba,
        
        [System.Xml.Serialization.XmlEnumAttribute("BB")]
        Bb,
        
        [System.Xml.Serialization.XmlEnumAttribute("BD")]
        Bd,
        
        [System.Xml.Serialization.XmlEnumAttribute("BE")]
        Be,
        
        [System.Xml.Serialization.XmlEnumAttribute("BF")]
        Bf,
        
        [System.Xml.Serialization.XmlEnumAttribute("BG")]
        Bg,
        
        [System.Xml.Serialization.XmlEnumAttribute("BH")]
        Bh,
        
        [System.Xml.Serialization.XmlEnumAttribute("BI")]
        Bi,
        
        [System.Xml.Serialization.XmlEnumAttribute("BJ")]
        Bj,
        
        [System.Xml.Serialization.XmlEnumAttribute("BL")]
        Bl,
        
        [System.Xml.Serialization.XmlEnumAttribute("BM")]
        Bm,
        
        [System.Xml.Serialization.XmlEnumAttribute("BN")]
        Bn,
        
        [System.Xml.Serialization.XmlEnumAttribute("BO")]
        Bo,
        
        [System.Xml.Serialization.XmlEnumAttribute("BR")]
        Br,
        
        [System.Xml.Serialization.XmlEnumAttribute("BS")]
        Bs,
        
        [System.Xml.Serialization.XmlEnumAttribute("BT")]
        Bt,
        
        [System.Xml.Serialization.XmlEnumAttribute("BV")]
        Bv,
        
        [System.Xml.Serialization.XmlEnumAttribute("BW")]
        Bw,
        
        [System.Xml.Serialization.XmlEnumAttribute("BY")]
        By,
        
        [System.Xml.Serialization.XmlEnumAttribute("BZ")]
        Bz,
        
        [System.Xml.Serialization.XmlEnumAttribute("CA")]
        Ca,
        
        [System.Xml.Serialization.XmlEnumAttribute("CC")]
        Cc,
        
        [System.Xml.Serialization.XmlEnumAttribute("CD")]
        Cd,
        
        [System.Xml.Serialization.XmlEnumAttribute("CF")]
        Cf,
        
        [System.Xml.Serialization.XmlEnumAttribute("CG")]
        Cg,
        
        [System.Xml.Serialization.XmlEnumAttribute("CH")]
        Ch,
        
        [System.Xml.Serialization.XmlEnumAttribute("CI")]
        Ci,
        
        [System.Xml.Serialization.XmlEnumAttribute("CK")]
        Ck,
        
        [System.Xml.Serialization.XmlEnumAttribute("CL")]
        Cl,
        
        [System.Xml.Serialization.XmlEnumAttribute("CM")]
        Cm,
        
        [System.Xml.Serialization.XmlEnumAttribute("CN")]
        Cn,
        
        [System.Xml.Serialization.XmlEnumAttribute("CO")]
        Co,
        
        [System.Xml.Serialization.XmlEnumAttribute("CR")]
        Cr,
        
        [System.Xml.Serialization.XmlEnumAttribute("CU")]
        Cu,
        
        [System.Xml.Serialization.XmlEnumAttribute("CV")]
        Cv,
        
        [System.Xml.Serialization.XmlEnumAttribute("CX")]
        Cx,
        
        [System.Xml.Serialization.XmlEnumAttribute("CY")]
        Cy,
        
        [System.Xml.Serialization.XmlEnumAttribute("CZ")]
        Cz,
        
        [System.Xml.Serialization.XmlEnumAttribute("DE")]
        De,
        
        [System.Xml.Serialization.XmlEnumAttribute("DJ")]
        Dj,
        
        [System.Xml.Serialization.XmlEnumAttribute("DK")]
        Dk,
        
        [System.Xml.Serialization.XmlEnumAttribute("DM")]
        Dm,
        
        [System.Xml.Serialization.XmlEnumAttribute("DO")]
        Do,
        
        [System.Xml.Serialization.XmlEnumAttribute("DZ")]
        Dz,
        
        [System.Xml.Serialization.XmlEnumAttribute("EC")]
        Ec,
        
        [System.Xml.Serialization.XmlEnumAttribute("EE")]
        Ee,
        
        [System.Xml.Serialization.XmlEnumAttribute("EG")]
        Eg,
        
        [System.Xml.Serialization.XmlEnumAttribute("EH")]
        Eh,
        
        [System.Xml.Serialization.XmlEnumAttribute("ER")]
        Er,
        
        [System.Xml.Serialization.XmlEnumAttribute("ES")]
        Es,
        
        [System.Xml.Serialization.XmlEnumAttribute("ET")]
        Et,
        
        [System.Xml.Serialization.XmlEnumAttribute("FI")]
        Fi,
        
        [System.Xml.Serialization.XmlEnumAttribute("FJ")]
        Fj,
        
        [System.Xml.Serialization.XmlEnumAttribute("FK")]
        Fk,
        
        [System.Xml.Serialization.XmlEnumAttribute("FM")]
        Fm,
        
        [System.Xml.Serialization.XmlEnumAttribute("FO")]
        Fo,
        
        [System.Xml.Serialization.XmlEnumAttribute("FR")]
        Fr,
        
        [System.Xml.Serialization.XmlEnumAttribute("GA")]
        Ga,
        
        [System.Xml.Serialization.XmlEnumAttribute("GB")]
        Gb,
        
        [System.Xml.Serialization.XmlEnumAttribute("GD")]
        Gd,
        
        [System.Xml.Serialization.XmlEnumAttribute("GE")]
        Ge,
        
        [System.Xml.Serialization.XmlEnumAttribute("GF")]
        Gf,
        
        [System.Xml.Serialization.XmlEnumAttribute("GG")]
        Gg,
        
        [System.Xml.Serialization.XmlEnumAttribute("GH")]
        Gh,
        
        [System.Xml.Serialization.XmlEnumAttribute("GI")]
        Gi,
        
        [System.Xml.Serialization.XmlEnumAttribute("GL")]
        Gl,
        
        [System.Xml.Serialization.XmlEnumAttribute("GM")]
        Gm,
        
        [System.Xml.Serialization.XmlEnumAttribute("GN")]
        Gn,
        
        [System.Xml.Serialization.XmlEnumAttribute("GP")]
        Gp,
        
        [System.Xml.Serialization.XmlEnumAttribute("GQ")]
        Gq,
        
        [System.Xml.Serialization.XmlEnumAttribute("GR")]
        Gr,
        
        [System.Xml.Serialization.XmlEnumAttribute("GS")]
        Gs,
        
        [System.Xml.Serialization.XmlEnumAttribute("GT")]
        Gt,
        
        [System.Xml.Serialization.XmlEnumAttribute("GU")]
        Gu,
        
        [System.Xml.Serialization.XmlEnumAttribute("GW")]
        Gw,
        
        [System.Xml.Serialization.XmlEnumAttribute("GY")]
        Gy,
        
        [System.Xml.Serialization.XmlEnumAttribute("HK")]
        Hk,
        
        [System.Xml.Serialization.XmlEnumAttribute("HM")]
        Hm,
        
        [System.Xml.Serialization.XmlEnumAttribute("HN")]
        Hn,
        
        [System.Xml.Serialization.XmlEnumAttribute("HR")]
        Hr,
        
        [System.Xml.Serialization.XmlEnumAttribute("HT")]
        Ht,
        
        [System.Xml.Serialization.XmlEnumAttribute("HU")]
        Hu,
        
        [System.Xml.Serialization.XmlEnumAttribute("ID")]
        Id,
        
        [System.Xml.Serialization.XmlEnumAttribute("IE")]
        Ie,
        
        [System.Xml.Serialization.XmlEnumAttribute("IL")]
        Il,
        
        [System.Xml.Serialization.XmlEnumAttribute("IM")]
        Im,
        
        [System.Xml.Serialization.XmlEnumAttribute("IN")]
        In,
        
        [System.Xml.Serialization.XmlEnumAttribute("IO")]
        Io,
        
        [System.Xml.Serialization.XmlEnumAttribute("IQ")]
        Iq,
        
        [System.Xml.Serialization.XmlEnumAttribute("IR")]
        Ir,
        
        [System.Xml.Serialization.XmlEnumAttribute("IS")]
        Is,
        
        [System.Xml.Serialization.XmlEnumAttribute("IT")]
        It,
        
        [System.Xml.Serialization.XmlEnumAttribute("JE")]
        Je,
        
        [System.Xml.Serialization.XmlEnumAttribute("JM")]
        Jm,
        
        [System.Xml.Serialization.XmlEnumAttribute("JO")]
        Jo,
        
        [System.Xml.Serialization.XmlEnumAttribute("JP")]
        Jp,
        
        [System.Xml.Serialization.XmlEnumAttribute("KE")]
        Ke,
        
        [System.Xml.Serialization.XmlEnumAttribute("KG")]
        Kg,
        
        [System.Xml.Serialization.XmlEnumAttribute("KH")]
        Kh,
        
        [System.Xml.Serialization.XmlEnumAttribute("KI")]
        Ki,
        
        [System.Xml.Serialization.XmlEnumAttribute("KM")]
        Km,
        
        [System.Xml.Serialization.XmlEnumAttribute("KN")]
        Kn,
        
        [System.Xml.Serialization.XmlEnumAttribute("KP")]
        Kp,
        
        [System.Xml.Serialization.XmlEnumAttribute("KR")]
        Kr,
        
        [System.Xml.Serialization.XmlEnumAttribute("KW")]
        Kw,
        
        [System.Xml.Serialization.XmlEnumAttribute("KY")]
        Ky,
        
        [System.Xml.Serialization.XmlEnumAttribute("KZ")]
        Kz,
        
        [System.Xml.Serialization.XmlEnumAttribute("LA")]
        La,
        
        [System.Xml.Serialization.XmlEnumAttribute("LB")]
        Lb,
        
        [System.Xml.Serialization.XmlEnumAttribute("LC")]
        Lc,
        
        [System.Xml.Serialization.XmlEnumAttribute("LI")]
        Li,
        
        [System.Xml.Serialization.XmlEnumAttribute("LK")]
        Lk,
        
        [System.Xml.Serialization.XmlEnumAttribute("LR")]
        Lr,
        
        [System.Xml.Serialization.XmlEnumAttribute("LS")]
        Ls,
        
        [System.Xml.Serialization.XmlEnumAttribute("LT")]
        Lt,
        
        [System.Xml.Serialization.XmlEnumAttribute("LU")]
        Lu,
        
        [System.Xml.Serialization.XmlEnumAttribute("LV")]
        Lv,
        
        [System.Xml.Serialization.XmlEnumAttribute("LY")]
        Ly,
        
        [System.Xml.Serialization.XmlEnumAttribute("MA")]
        Ma,
        
        [System.Xml.Serialization.XmlEnumAttribute("MC")]
        Mc,
        
        [System.Xml.Serialization.XmlEnumAttribute("MD")]
        Md,
        
        [System.Xml.Serialization.XmlEnumAttribute("ME")]
        Me,
        
        [System.Xml.Serialization.XmlEnumAttribute("MF")]
        Mf,
        
        [System.Xml.Serialization.XmlEnumAttribute("MG")]
        Mg,
        
        [System.Xml.Serialization.XmlEnumAttribute("MH")]
        Mh,
        
        [System.Xml.Serialization.XmlEnumAttribute("MK")]
        Mk,
        
        [System.Xml.Serialization.XmlEnumAttribute("ML")]
        Ml,
        
        [System.Xml.Serialization.XmlEnumAttribute("MM")]
        Mm,
        
        [System.Xml.Serialization.XmlEnumAttribute("MN")]
        Mn,
        
        [System.Xml.Serialization.XmlEnumAttribute("MO")]
        Mo,
        
        [System.Xml.Serialization.XmlEnumAttribute("MP")]
        Mp,
        
        [System.Xml.Serialization.XmlEnumAttribute("MQ")]
        Mq,
        
        [System.Xml.Serialization.XmlEnumAttribute("MR")]
        Mr,
        
        [System.Xml.Serialization.XmlEnumAttribute("MS")]
        Ms,
        
        [System.Xml.Serialization.XmlEnumAttribute("MT")]
        Mt,
        
        [System.Xml.Serialization.XmlEnumAttribute("MU")]
        Mu,
        
        [System.Xml.Serialization.XmlEnumAttribute("MV")]
        Mv,
        
        [System.Xml.Serialization.XmlEnumAttribute("MW")]
        Mw,
        
        [System.Xml.Serialization.XmlEnumAttribute("MX")]
        Mx,
        
        [System.Xml.Serialization.XmlEnumAttribute("MY")]
        My,
        
        [System.Xml.Serialization.XmlEnumAttribute("MZ")]
        Mz,
        
        [System.Xml.Serialization.XmlEnumAttribute("NA")]
        Na,
        
        [System.Xml.Serialization.XmlEnumAttribute("NC")]
        Nc,
        
        [System.Xml.Serialization.XmlEnumAttribute("NE")]
        Ne,
        
        [System.Xml.Serialization.XmlEnumAttribute("NF")]
        Nf,
        
        [System.Xml.Serialization.XmlEnumAttribute("NG")]
        Ng,
        
        [System.Xml.Serialization.XmlEnumAttribute("NI")]
        Ni,
        
        [System.Xml.Serialization.XmlEnumAttribute("NL")]
        Nl,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO")]
        No,
        
        [System.Xml.Serialization.XmlEnumAttribute("NP")]
        Np,
        
        [System.Xml.Serialization.XmlEnumAttribute("NR")]
        Nr,
        
        [System.Xml.Serialization.XmlEnumAttribute("NU")]
        Nu,
        
        [System.Xml.Serialization.XmlEnumAttribute("NZ")]
        Nz,
        
        [System.Xml.Serialization.XmlEnumAttribute("OC")]
        Oc,
        
        [System.Xml.Serialization.XmlEnumAttribute("OM")]
        Om,
        
        [System.Xml.Serialization.XmlEnumAttribute("PA")]
        Pa,
        
        [System.Xml.Serialization.XmlEnumAttribute("PE")]
        Pe,
        
        [System.Xml.Serialization.XmlEnumAttribute("PF")]
        Pf,
        
        [System.Xml.Serialization.XmlEnumAttribute("PG")]
        Pg,
        
        [System.Xml.Serialization.XmlEnumAttribute("PH")]
        Ph,
        
        [System.Xml.Serialization.XmlEnumAttribute("PK")]
        Pk,
        
        [System.Xml.Serialization.XmlEnumAttribute("PL")]
        Pl,
        
        [System.Xml.Serialization.XmlEnumAttribute("PM")]
        Pm,
        
        [System.Xml.Serialization.XmlEnumAttribute("PN")]
        Pn,
        
        [System.Xml.Serialization.XmlEnumAttribute("PR")]
        Pr,
        
        [System.Xml.Serialization.XmlEnumAttribute("PS")]
        Ps,
        
        [System.Xml.Serialization.XmlEnumAttribute("PT")]
        Pt,
        
        [System.Xml.Serialization.XmlEnumAttribute("PW")]
        Pw,
        
        [System.Xml.Serialization.XmlEnumAttribute("PY")]
        Py,
        
        [System.Xml.Serialization.XmlEnumAttribute("QA")]
        Qa,
        
        [System.Xml.Serialization.XmlEnumAttribute("RE")]
        Re,
        
        [System.Xml.Serialization.XmlEnumAttribute("RO")]
        Ro,
        
        [System.Xml.Serialization.XmlEnumAttribute("RS")]
        Rs,
        
        [System.Xml.Serialization.XmlEnumAttribute("RU")]
        Ru,
        
        [System.Xml.Serialization.XmlEnumAttribute("RW")]
        Rw,
        
        [System.Xml.Serialization.XmlEnumAttribute("SA")]
        Sa,
        
        [System.Xml.Serialization.XmlEnumAttribute("SB")]
        Sb,
        
        [System.Xml.Serialization.XmlEnumAttribute("SC")]
        Sc,
        
        [System.Xml.Serialization.XmlEnumAttribute("SD")]
        Sd,
        
        [System.Xml.Serialization.XmlEnumAttribute("SE")]
        Se,
        
        [System.Xml.Serialization.XmlEnumAttribute("SG")]
        Sg,
        
        [System.Xml.Serialization.XmlEnumAttribute("SH")]
        Sh,
        
        [System.Xml.Serialization.XmlEnumAttribute("SI")]
        Si,
        
        [System.Xml.Serialization.XmlEnumAttribute("SJ")]
        Sj,
        
        [System.Xml.Serialization.XmlEnumAttribute("SK")]
        Sk,
        
        [System.Xml.Serialization.XmlEnumAttribute("SL")]
        Sl,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM")]
        Sm,
        
        [System.Xml.Serialization.XmlEnumAttribute("SN")]
        Sn,
        
        [System.Xml.Serialization.XmlEnumAttribute("SO")]
        So,
        
        [System.Xml.Serialization.XmlEnumAttribute("SR")]
        Sr,
        
        [System.Xml.Serialization.XmlEnumAttribute("ST")]
        St,
        
        [System.Xml.Serialization.XmlEnumAttribute("SV")]
        Sv,
        
        [System.Xml.Serialization.XmlEnumAttribute("SY")]
        Sy,
        
        [System.Xml.Serialization.XmlEnumAttribute("SZ")]
        Sz,
        
        [System.Xml.Serialization.XmlEnumAttribute("TC")]
        Tc,
        
        [System.Xml.Serialization.XmlEnumAttribute("TD")]
        Td,
        
        [System.Xml.Serialization.XmlEnumAttribute("TF")]
        Tf,
        
        [System.Xml.Serialization.XmlEnumAttribute("TG")]
        Tg,
        
        [System.Xml.Serialization.XmlEnumAttribute("TH")]
        Th,
        
        [System.Xml.Serialization.XmlEnumAttribute("TJ")]
        Tj,
        
        [System.Xml.Serialization.XmlEnumAttribute("TK")]
        Tk,
        
        [System.Xml.Serialization.XmlEnumAttribute("TL")]
        Tl,
        
        [System.Xml.Serialization.XmlEnumAttribute("TM")]
        Tm,
        
        [System.Xml.Serialization.XmlEnumAttribute("TN")]
        Tn,
        
        [System.Xml.Serialization.XmlEnumAttribute("TO")]
        To,
        
        [System.Xml.Serialization.XmlEnumAttribute("TR")]
        Tr,
        
        [System.Xml.Serialization.XmlEnumAttribute("TT")]
        Tt,
        
        [System.Xml.Serialization.XmlEnumAttribute("TV")]
        Tv,
        
        [System.Xml.Serialization.XmlEnumAttribute("TW")]
        Tw,
        
        [System.Xml.Serialization.XmlEnumAttribute("TZ")]
        Tz,
        
        [System.Xml.Serialization.XmlEnumAttribute("UA")]
        Ua,
        
        [System.Xml.Serialization.XmlEnumAttribute("UG")]
        Ug,
        
        [System.Xml.Serialization.XmlEnumAttribute("UM")]
        Um,
        
        [System.Xml.Serialization.XmlEnumAttribute("US")]
        Us,
        
        [System.Xml.Serialization.XmlEnumAttribute("UY")]
        Uy,
        
        [System.Xml.Serialization.XmlEnumAttribute("UZ")]
        Uz,
        
        [System.Xml.Serialization.XmlEnumAttribute("VA")]
        Va,
        
        [System.Xml.Serialization.XmlEnumAttribute("VC")]
        Vc,
        
        [System.Xml.Serialization.XmlEnumAttribute("VE")]
        Ve,
        
        [System.Xml.Serialization.XmlEnumAttribute("VG")]
        Vg,
        
        [System.Xml.Serialization.XmlEnumAttribute("VI")]
        Vi,
        
        [System.Xml.Serialization.XmlEnumAttribute("VN")]
        Vn,
        
        [System.Xml.Serialization.XmlEnumAttribute("VU")]
        Vu,
        
        [System.Xml.Serialization.XmlEnumAttribute("WF")]
        Wf,
        
        [System.Xml.Serialization.XmlEnumAttribute("WS")]
        Ws,
        
        [System.Xml.Serialization.XmlEnumAttribute("YE")]
        Ye,
        
        [System.Xml.Serialization.XmlEnumAttribute("YT")]
        Yt,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZA")]
        Za,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZM")]
        Zm,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZW")]
        Zw,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InvoiceType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("InvoiceType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum InvoiceType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,
        
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
        
        [System.Xml.Serialization.XmlEnumAttribute("1.3")]
        Item13,
        
        [System.Xml.Serialization.XmlEnumAttribute("1.4")]
        Item14,
        
        [System.Xml.Serialization.XmlEnumAttribute("1.5")]
        Item15,
        
        [System.Xml.Serialization.XmlEnumAttribute("1.6")]
        Item16,
        
        [System.Xml.Serialization.XmlEnumAttribute("2.1")]
        Item21,
        
        [System.Xml.Serialization.XmlEnumAttribute("2.2")]
        Item22,
        
        [System.Xml.Serialization.XmlEnumAttribute("2.3")]
        Item23,
        
        [System.Xml.Serialization.XmlEnumAttribute("2.4")]
        Item24,
        
        [System.Xml.Serialization.XmlEnumAttribute("3.1")]
        Item31,
        
        [System.Xml.Serialization.XmlEnumAttribute("3.2")]
        Item32,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5.1")]
        Item51,
        
        [System.Xml.Serialization.XmlEnumAttribute("5.2")]
        Item52,
        
        [System.Xml.Serialization.XmlEnumAttribute("6.1")]
        Item61,
        
        [System.Xml.Serialization.XmlEnumAttribute("6.2")]
        Item62,
        
        [System.Xml.Serialization.XmlEnumAttribute("7.1")]
        Item71,
        
        [System.Xml.Serialization.XmlEnumAttribute("8.1")]
        Item81,
        
        [System.Xml.Serialization.XmlEnumAttribute("8.2")]
        Item82,
        
        [System.Xml.Serialization.XmlEnumAttribute("8.4")]
        Item84,
        
        [System.Xml.Serialization.XmlEnumAttribute("8.5")]
        Item85,
        
        [System.Xml.Serialization.XmlEnumAttribute("8.6")]
        Item86,
        
        [System.Xml.Serialization.XmlEnumAttribute("9.1")]
        Item91,
        
        [System.Xml.Serialization.XmlEnumAttribute("9.2")]
        Item92,
        
        [System.Xml.Serialization.XmlEnumAttribute("9.3")]
        Item93,
        
        [System.Xml.Serialization.XmlEnumAttribute("10.1")]
        Item101,
        
        [System.Xml.Serialization.XmlEnumAttribute("10.2")]
        Item102,
        
        [System.Xml.Serialization.XmlEnumAttribute("11.1")]
        Item111,
        
        [System.Xml.Serialization.XmlEnumAttribute("11.2")]
        Item112,
        
        [System.Xml.Serialization.XmlEnumAttribute("11.3")]
        Item113,
        
        [System.Xml.Serialization.XmlEnumAttribute("11.4")]
        Item114,
        
        [System.Xml.Serialization.XmlEnumAttribute("11.5")]
        Item115,
        
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item121,
        
        [System.Xml.Serialization.XmlEnumAttribute("13.1")]
        Item131,
        
        [System.Xml.Serialization.XmlEnumAttribute("13.2")]
        Item132,
        
        [System.Xml.Serialization.XmlEnumAttribute("13.3")]
        Item133,
        
        [System.Xml.Serialization.XmlEnumAttribute("13.4")]
        Item134,
        
        [System.Xml.Serialization.XmlEnumAttribute("13.30")]
        Item1330,
        
        [System.Xml.Serialization.XmlEnumAttribute("13.31")]
        Item1331,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.1")]
        Item141,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.2")]
        Item142,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.3")]
        Item143,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.4")]
        Item144,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.5")]
        Item145,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.30")]
        Item1430,
        
        [System.Xml.Serialization.XmlEnumAttribute("14.31")]
        Item1431,
        
        [System.Xml.Serialization.XmlEnumAttribute("15.1")]
        Item151,
        
        [System.Xml.Serialization.XmlEnumAttribute("16.1")]
        Item161,
        
        [System.Xml.Serialization.XmlEnumAttribute("17.1")]
        Item171,
        
        [System.Xml.Serialization.XmlEnumAttribute("17.2")]
        Item172,
        
        [System.Xml.Serialization.XmlEnumAttribute("17.3")]
        Item173,
        
        [System.Xml.Serialization.XmlEnumAttribute("17.4")]
        Item174,
        
        [System.Xml.Serialization.XmlEnumAttribute("17.5")]
        Item175,
        
        [System.Xml.Serialization.XmlEnumAttribute("17.6")]
        Item176,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CurrencyType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("CurrencyType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum CurrencyType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("AED")]
        Aed,
        
        [System.Xml.Serialization.XmlEnumAttribute("AFN")]
        Afn,
        
        [System.Xml.Serialization.XmlEnumAttribute("ALL")]
        All,
        
        [System.Xml.Serialization.XmlEnumAttribute("AMD")]
        Amd,
        
        [System.Xml.Serialization.XmlEnumAttribute("ANG")]
        Ang,
        
        [System.Xml.Serialization.XmlEnumAttribute("AOA")]
        Aoa,
        
        [System.Xml.Serialization.XmlEnumAttribute("ARS")]
        Ars,
        
        [System.Xml.Serialization.XmlEnumAttribute("AUD")]
        Aud,
        
        [System.Xml.Serialization.XmlEnumAttribute("AWG")]
        Awg,
        
        [System.Xml.Serialization.XmlEnumAttribute("AZN")]
        Azn,
        
        [System.Xml.Serialization.XmlEnumAttribute("BAM")]
        Bam,
        
        [System.Xml.Serialization.XmlEnumAttribute("BBD")]
        Bbd,
        
        [System.Xml.Serialization.XmlEnumAttribute("BDT")]
        Bdt,
        
        [System.Xml.Serialization.XmlEnumAttribute("BGN")]
        Bgn,
        
        [System.Xml.Serialization.XmlEnumAttribute("BHD")]
        Bhd,
        
        [System.Xml.Serialization.XmlEnumAttribute("BIF")]
        Bif,
        
        [System.Xml.Serialization.XmlEnumAttribute("BMD")]
        Bmd,
        
        [System.Xml.Serialization.XmlEnumAttribute("BND")]
        Bnd,
        
        [System.Xml.Serialization.XmlEnumAttribute("BOB")]
        Bob,
        
        [System.Xml.Serialization.XmlEnumAttribute("BOV")]
        Bov,
        
        [System.Xml.Serialization.XmlEnumAttribute("BRL")]
        Brl,
        
        [System.Xml.Serialization.XmlEnumAttribute("BSD")]
        Bsd,
        
        [System.Xml.Serialization.XmlEnumAttribute("BTN")]
        Btn,
        
        [System.Xml.Serialization.XmlEnumAttribute("BWP")]
        Bwp,
        
        [System.Xml.Serialization.XmlEnumAttribute("BYR")]
        Byr,
        
        [System.Xml.Serialization.XmlEnumAttribute("BZD")]
        Bzd,
        
        [System.Xml.Serialization.XmlEnumAttribute("CAD")]
        Cad,
        
        [System.Xml.Serialization.XmlEnumAttribute("CDF")]
        Cdf,
        
        [System.Xml.Serialization.XmlEnumAttribute("CHF")]
        Chf,
        
        [System.Xml.Serialization.XmlEnumAttribute("CLF")]
        Clf,
        
        [System.Xml.Serialization.XmlEnumAttribute("CLP")]
        Clp,
        
        [System.Xml.Serialization.XmlEnumAttribute("CNY")]
        Cny,
        
        [System.Xml.Serialization.XmlEnumAttribute("COP")]
        Cop,
        
        [System.Xml.Serialization.XmlEnumAttribute("COU")]
        Cou,
        
        [System.Xml.Serialization.XmlEnumAttribute("CRC")]
        Crc,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUC")]
        Cuc,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUP")]
        Cup,
        
        [System.Xml.Serialization.XmlEnumAttribute("CVE")]
        Cve,
        
        [System.Xml.Serialization.XmlEnumAttribute("CZK")]
        Czk,
        
        [System.Xml.Serialization.XmlEnumAttribute("DJF")]
        Djf,
        
        [System.Xml.Serialization.XmlEnumAttribute("DKK")]
        Dkk,
        
        [System.Xml.Serialization.XmlEnumAttribute("DOP")]
        Dop,
        
        [System.Xml.Serialization.XmlEnumAttribute("DZD")]
        Dzd,
        
        [System.Xml.Serialization.XmlEnumAttribute("EEK")]
        Eek,
        
        [System.Xml.Serialization.XmlEnumAttribute("EGP")]
        Egp,
        
        [System.Xml.Serialization.XmlEnumAttribute("ERN")]
        Ern,
        
        [System.Xml.Serialization.XmlEnumAttribute("ETB")]
        Etb,
        
        [System.Xml.Serialization.XmlEnumAttribute("EUR")]
        Eur,
        
        [System.Xml.Serialization.XmlEnumAttribute("FJD")]
        Fjd,
        
        [System.Xml.Serialization.XmlEnumAttribute("FKP")]
        Fkp,
        
        [System.Xml.Serialization.XmlEnumAttribute("GBP")]
        Gbp,
        
        [System.Xml.Serialization.XmlEnumAttribute("GEL")]
        Gel,
        
        [System.Xml.Serialization.XmlEnumAttribute("GHS")]
        Ghs,
        
        [System.Xml.Serialization.XmlEnumAttribute("GIP")]
        Gip,
        
        [System.Xml.Serialization.XmlEnumAttribute("GMD")]
        Gmd,
        
        [System.Xml.Serialization.XmlEnumAttribute("GNF")]
        Gnf,
        
        [System.Xml.Serialization.XmlEnumAttribute("GTQ")]
        Gtq,
        
        [System.Xml.Serialization.XmlEnumAttribute("GWP")]
        Gwp,
        
        [System.Xml.Serialization.XmlEnumAttribute("GYD")]
        Gyd,
        
        [System.Xml.Serialization.XmlEnumAttribute("HKD")]
        Hkd,
        
        [System.Xml.Serialization.XmlEnumAttribute("HNL")]
        Hnl,
        
        [System.Xml.Serialization.XmlEnumAttribute("HRK")]
        Hrk,
        
        [System.Xml.Serialization.XmlEnumAttribute("HTG")]
        Htg,
        
        [System.Xml.Serialization.XmlEnumAttribute("HUF")]
        Huf,
        
        [System.Xml.Serialization.XmlEnumAttribute("IDR")]
        Idr,
        
        [System.Xml.Serialization.XmlEnumAttribute("ILS")]
        Ils,
        
        [System.Xml.Serialization.XmlEnumAttribute("INR")]
        Inr,
        
        [System.Xml.Serialization.XmlEnumAttribute("IQD")]
        Iqd,
        
        [System.Xml.Serialization.XmlEnumAttribute("IRR")]
        Irr,
        
        [System.Xml.Serialization.XmlEnumAttribute("ISK")]
        Isk,
        
        [System.Xml.Serialization.XmlEnumAttribute("JMD")]
        Jmd,
        
        [System.Xml.Serialization.XmlEnumAttribute("JOD")]
        Jod,
        
        [System.Xml.Serialization.XmlEnumAttribute("JPY")]
        Jpy,
        
        [System.Xml.Serialization.XmlEnumAttribute("KES")]
        Kes,
        
        [System.Xml.Serialization.XmlEnumAttribute("KGS")]
        Kgs,
        
        [System.Xml.Serialization.XmlEnumAttribute("KHR")]
        Khr,
        
        [System.Xml.Serialization.XmlEnumAttribute("KMF")]
        Kmf,
        
        [System.Xml.Serialization.XmlEnumAttribute("KPW")]
        Kpw,
        
        [System.Xml.Serialization.XmlEnumAttribute("KRW")]
        Krw,
        
        [System.Xml.Serialization.XmlEnumAttribute("KWD")]
        Kwd,
        
        [System.Xml.Serialization.XmlEnumAttribute("KYD")]
        Kyd,
        
        [System.Xml.Serialization.XmlEnumAttribute("KZT")]
        Kzt,
        
        [System.Xml.Serialization.XmlEnumAttribute("LAK")]
        Lak,
        
        [System.Xml.Serialization.XmlEnumAttribute("LBP")]
        Lbp,
        
        [System.Xml.Serialization.XmlEnumAttribute("LKR")]
        Lkr,
        
        [System.Xml.Serialization.XmlEnumAttribute("LRD")]
        Lrd,
        
        [System.Xml.Serialization.XmlEnumAttribute("LSL")]
        Lsl,
        
        [System.Xml.Serialization.XmlEnumAttribute("LTL")]
        Ltl,
        
        [System.Xml.Serialization.XmlEnumAttribute("LVL")]
        Lvl,
        
        [System.Xml.Serialization.XmlEnumAttribute("LYD")]
        Lyd,
        
        [System.Xml.Serialization.XmlEnumAttribute("MAD")]
        Mad,
        
        [System.Xml.Serialization.XmlEnumAttribute("MDL")]
        Mdl,
        
        [System.Xml.Serialization.XmlEnumAttribute("MGA")]
        Mga,
        
        [System.Xml.Serialization.XmlEnumAttribute("MKD")]
        Mkd,
        
        [System.Xml.Serialization.XmlEnumAttribute("MMK")]
        Mmk,
        
        [System.Xml.Serialization.XmlEnumAttribute("MNT")]
        Mnt,
        
        [System.Xml.Serialization.XmlEnumAttribute("MOP")]
        Mop,
        
        [System.Xml.Serialization.XmlEnumAttribute("MRO")]
        Mro,
        
        [System.Xml.Serialization.XmlEnumAttribute("MUR")]
        Mur,
        
        [System.Xml.Serialization.XmlEnumAttribute("MVR")]
        Mvr,
        
        [System.Xml.Serialization.XmlEnumAttribute("MWK")]
        Mwk,
        
        [System.Xml.Serialization.XmlEnumAttribute("MXN")]
        Mxn,
        
        [System.Xml.Serialization.XmlEnumAttribute("MXV")]
        Mxv,
        
        [System.Xml.Serialization.XmlEnumAttribute("MYR")]
        Myr,
        
        [System.Xml.Serialization.XmlEnumAttribute("MZN")]
        Mzn,
        
        [System.Xml.Serialization.XmlEnumAttribute("NAD")]
        Nad,
        
        [System.Xml.Serialization.XmlEnumAttribute("NGN")]
        Ngn,
        
        [System.Xml.Serialization.XmlEnumAttribute("NIO")]
        Nio,
        
        [System.Xml.Serialization.XmlEnumAttribute("NOK")]
        Nok,
        
        [System.Xml.Serialization.XmlEnumAttribute("NPR")]
        Npr,
        
        [System.Xml.Serialization.XmlEnumAttribute("NZD")]
        Nzd,
        
        [System.Xml.Serialization.XmlEnumAttribute("OMR")]
        Omr,
        
        [System.Xml.Serialization.XmlEnumAttribute("PAB")]
        Pab,
        
        [System.Xml.Serialization.XmlEnumAttribute("PEN")]
        Pen,
        
        [System.Xml.Serialization.XmlEnumAttribute("PGK")]
        Pgk,
        
        [System.Xml.Serialization.XmlEnumAttribute("PHP")]
        Php,
        
        [System.Xml.Serialization.XmlEnumAttribute("PKR")]
        Pkr,
        
        [System.Xml.Serialization.XmlEnumAttribute("PLN")]
        Pln,
        
        [System.Xml.Serialization.XmlEnumAttribute("PYG")]
        Pyg,
        
        [System.Xml.Serialization.XmlEnumAttribute("QAR")]
        Qar,
        
        [System.Xml.Serialization.XmlEnumAttribute("RON")]
        Ron,
        
        [System.Xml.Serialization.XmlEnumAttribute("RSD")]
        Rsd,
        
        [System.Xml.Serialization.XmlEnumAttribute("RUB")]
        Rub,
        
        [System.Xml.Serialization.XmlEnumAttribute("RWF")]
        Rwf,
        
        [System.Xml.Serialization.XmlEnumAttribute("SAR")]
        Sar,
        
        [System.Xml.Serialization.XmlEnumAttribute("SBD")]
        Sbd,
        
        [System.Xml.Serialization.XmlEnumAttribute("SCR")]
        Scr,
        
        [System.Xml.Serialization.XmlEnumAttribute("SDG")]
        Sdg,
        
        [System.Xml.Serialization.XmlEnumAttribute("SEK")]
        Sek,
        
        [System.Xml.Serialization.XmlEnumAttribute("SGD")]
        Sgd,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHP")]
        Shp,
        
        [System.Xml.Serialization.XmlEnumAttribute("SLL")]
        Sll,
        
        [System.Xml.Serialization.XmlEnumAttribute("SOS")]
        Sos,
        
        [System.Xml.Serialization.XmlEnumAttribute("SRD")]
        Srd,
        
        [System.Xml.Serialization.XmlEnumAttribute("STD")]
        Std,
        
        [System.Xml.Serialization.XmlEnumAttribute("SVC")]
        Svc,
        
        [System.Xml.Serialization.XmlEnumAttribute("SYP")]
        Syp,
        
        [System.Xml.Serialization.XmlEnumAttribute("SZL")]
        Szl,
        
        [System.Xml.Serialization.XmlEnumAttribute("THB")]
        Thb,
        
        [System.Xml.Serialization.XmlEnumAttribute("TJS")]
        Tjs,
        
        [System.Xml.Serialization.XmlEnumAttribute("TMT")]
        Tmt,
        
        [System.Xml.Serialization.XmlEnumAttribute("TND")]
        Tnd,
        
        [System.Xml.Serialization.XmlEnumAttribute("TOP")]
        Top,
        
        [System.Xml.Serialization.XmlEnumAttribute("TRY")]
        Try,
        
        [System.Xml.Serialization.XmlEnumAttribute("TTD")]
        Ttd,
        
        [System.Xml.Serialization.XmlEnumAttribute("TVD")]
        Tvd,
        
        [System.Xml.Serialization.XmlEnumAttribute("TWD")]
        Twd,
        
        [System.Xml.Serialization.XmlEnumAttribute("TZS")]
        Tzs,
        
        [System.Xml.Serialization.XmlEnumAttribute("UAH")]
        Uah,
        
        [System.Xml.Serialization.XmlEnumAttribute("UGX")]
        Ugx,
        
        [System.Xml.Serialization.XmlEnumAttribute("USD")]
        Usd,
        
        [System.Xml.Serialization.XmlEnumAttribute("UYU")]
        Uyu,
        
        [System.Xml.Serialization.XmlEnumAttribute("UZS")]
        Uzs,
        
        [System.Xml.Serialization.XmlEnumAttribute("VEF")]
        Vef,
        
        [System.Xml.Serialization.XmlEnumAttribute("VND")]
        Vnd,
        
        [System.Xml.Serialization.XmlEnumAttribute("VUV")]
        Vuv,
        
        [System.Xml.Serialization.XmlEnumAttribute("WST")]
        Wst,
        
        [System.Xml.Serialization.XmlEnumAttribute("XAF")]
        Xaf,
        
        [System.Xml.Serialization.XmlEnumAttribute("XCD")]
        Xcd,
        
        [System.Xml.Serialization.XmlEnumAttribute("XOF")]
        Xof,
        
        [System.Xml.Serialization.XmlEnumAttribute("XPD")]
        Xpd,
        
        [System.Xml.Serialization.XmlEnumAttribute("XPF")]
        Xpf,
        
        [System.Xml.Serialization.XmlEnumAttribute("YER")]
        Yer,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZAR")]
        Zar,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZMK")]
        Zmk,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZWL")]
        Zwl,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeliveryOutcomeType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("DeliveryOutcomeType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum DeliveryOutcomeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("FULL")]
        Full,
        
        [System.Xml.Serialization.XmlEnumAttribute("PARTIAL")]
        Partial,
        
        [System.Xml.Serialization.XmlEnumAttribute("NONE")]
        None,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FuelCodes", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("FuelCodes", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum FuelCodes
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        
        [System.Xml.Serialization.XmlEnumAttribute("999")]
        Item999,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExpensesClassificationValueType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("ExpensesClassificationValueType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum ExpensesClassificationValueType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_101")]
        E3101,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_001")]
        E3102001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_002")]
        E3102002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_003")]
        E3102003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_004")]
        E3102004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_005")]
        E3102005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_006")]
        E3102006,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_104")]
        E3104,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_201")]
        E3201,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_001")]
        E3202001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_002")]
        E3202002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_003")]
        E3202003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_004")]
        E3202004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_005")]
        E3202005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_204")]
        E3204,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_207")]
        E3207,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_209")]
        E3209,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_301")]
        E3301,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_001")]
        E3302001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_002")]
        E3302002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_003")]
        E3302003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_004")]
        E3302004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_005")]
        E3302005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_304")]
        E3304,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_307")]
        E3307,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_309")]
        E3309,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_312")]
        E3312,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_001")]
        E3313001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_002")]
        E3313002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_003")]
        E3313003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_004")]
        E3313004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_005")]
        E3313005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_315")]
        E3315,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_581_001")]
        E3581001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_581_002")]
        E3581002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_581_003")]
        E3581003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_582")]
        E3582,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_583")]
        E3583,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_584")]
        E3584,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_001")]
        E3585001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_002")]
        E3585002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_003")]
        E3585003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_004")]
        E3585004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_005")]
        E3585005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_006")]
        E3585006,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_007")]
        E3585007,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_008")]
        E3585008,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_009")]
        E3585009,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_010")]
        E3585010,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_011")]
        E3585011,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_012")]
        E3585012,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_013")]
        E3585013,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_014")]
        E3585014,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_015")]
        E3585015,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_016")]
        E3585016,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_586")]
        E3586,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_587")]
        E3587,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_588")]
        E3588,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_589")]
        E3589,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_001")]
        E3881001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_002")]
        E3881002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_003")]
        E3881003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_004")]
        E3881004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_001")]
        E3882001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_002")]
        E3882002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_003")]
        E3882003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_004")]
        E3882004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_001")]
        E3883001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_002")]
        E3883002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_003")]
        E3883003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_004")]
        E3883004,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_361")]
        Vat361,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_362")]
        Vat362,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_363")]
        Vat363,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_364")]
        Vat364,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_365")]
        Vat365,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_366")]
        Vat366,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_103")]
        E3103,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_203")]
        E3203,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_303")]
        E3303,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_208")]
        E3208,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_308")]
        E3308,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_314")]
        E3314,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_106")]
        E3106,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_205")]
        E3205,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_305")]
        E3305,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_210")]
        E3210,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_310")]
        E3310,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_318")]
        E3318,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_598_002")]
        E3598002,
        
        [System.Xml.Serialization.XmlEnumAttribute("NOT_VAT_295")]
        NotVat295,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExpensesClassificationCategoryType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("ExpensesClassificationCategoryType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum ExpensesClassificationCategoryType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_1")]
        Category21,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_2")]
        Category22,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_3")]
        Category23,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_4")]
        Category24,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_5")]
        Category25,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_6")]
        Category26,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_7")]
        Category27,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_8")]
        Category28,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_9")]
        Category29,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_10")]
        Category210,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_11")]
        Category211,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_12")]
        Category212,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_13")]
        Category213,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_14")]
        Category214,
        
        [System.Xml.Serialization.XmlEnumAttribute("category2_95")]
        Category295,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InvoiceExpensesClassificationType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceExpensesClassificationType
    {
        
        [System.ComponentModel.DescriptionAttribute("Μοναδικός Αριθμός Καταχώρησης Παραστατικού")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("invoiceMark")]
        public long InvoiceMark { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Αποδεικτικό Λήψης Χαρακτηρισμού Εξόδων. Συμπληρώνεται από την Υπηρεσία")]
        [System.Xml.Serialization.XmlElementAttribute("classificationMark")]
        public long ClassificationMark { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationMarkSpecified { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("ΑΦΜ Οντότητας Αναφοράς")]
        [System.Xml.Serialization.XmlElementAttribute("entityVatNumber")]
        public string EntityVatNumber { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Αιτιολογία Συναλλαγής")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "1", "2")]
        [System.Xml.Serialization.XmlElementAttribute("transactionMode")]
        public int TransactionMode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionModeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InvoicesExpensesClassificationDetailType> _invoicesExpensesClassificationDetails;
        
        [System.Xml.Serialization.XmlElementAttribute("invoicesExpensesClassificationDetails")]
        public System.Collections.ObjectModel.Collection<InvoicesExpensesClassificationDetailType> InvoicesExpensesClassificationDetails
        {
            get
            {
                return _invoicesExpensesClassificationDetails;
            }
            private set
            {
                _invoicesExpensesClassificationDetails = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoicesExpensesClassificationDetailsSpecified
        {
            get
            {
                return (this.InvoicesExpensesClassificationDetails.Count != 0);
            }
        }
        
        public InvoiceExpensesClassificationType()
        {
            this._invoicesExpensesClassificationDetails = new System.Collections.ObjectModel.Collection<InvoicesExpensesClassificationDetailType>();
        }
        
        [System.ComponentModel.DescriptionAttribute("Μέθοδος Υποβολής Χαρακτηρισμού")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(sbyte), "0", "1")]
        [System.Xml.Serialization.XmlElementAttribute("classificationPostMode")]
        public sbyte ClassificationPostMode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationPostModeSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InvoicesExpensesClassificationDetailType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoicesExpensesClassificationDetailType
    {
        
        [System.ComponentModel.DescriptionAttribute("Γραμμή Παραστατικού")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("lineNumber")]
        public int LineNumber { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ExpensesClassificationType> _expensesClassificationDetailData;
        
        [System.ComponentModel.DescriptionAttribute("Λίστα Χαρακτηρισμών Εσόδων")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("expensesClassificationDetailData")]
        public System.Collections.ObjectModel.Collection<ExpensesClassificationType> ExpensesClassificationDetailData
        {
            get
            {
                return _expensesClassificationDetailData;
            }
            private set
            {
                _expensesClassificationDetailData = value;
            }
        }
        
        public InvoicesExpensesClassificationDetailType()
        {
            this._expensesClassificationDetailData = new System.Collections.ObjectModel.Collection<ExpensesClassificationType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExpensesClassificationType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExpensesClassificationType
    {
        
        [System.ComponentModel.DescriptionAttribute("Κωδικός Χαρακτηρισμού")]
        [System.Xml.Serialization.XmlElementAttribute("classificationType")]
        public ExpensesClassificationTypeClassificationType ClassificationType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationTypeSpecified { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Κατηγορία Χαρακτηρισμού")]
        [System.Xml.Serialization.XmlElementAttribute("classificationCategory")]
        public Gr.Aade.MyData.ExpensesClassificaton.V1._0.ExpensesClassificationCategoryType ClassificationCategory { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationCategorySpecified { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Ποσό Χαρακτηρισμού")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public decimal Amount { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Πόσο Φόρου")]
        [System.Xml.Serialization.XmlElementAttribute("vatAmount")]
        public decimal VatAmount { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatAmountSpecified { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Κατηγορία ΦΠΑ")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "1", "10")]
        [System.Xml.Serialization.XmlElementAttribute("vatCategory")]
        public int VatCategory { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatCategorySpecified { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Κατηγορία Εξαίρεσης ΦΠΑ")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "1", "31")]
        [System.Xml.Serialization.XmlElementAttribute("vatExemptionCategory")]
        public int VatExemptionCategory { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatExemptionCategorySpecified { get; set; }
        
        [System.ComponentModel.DescriptionAttribute("Μοναδικός Αριθμός Χαρακτηρισμού")]
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public sbyte Id { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExpensesClassificationTypeClassificationType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0", AnonymousType=true)]
    public enum ExpensesClassificationTypeClassificationType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_101")]
        E3101,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_001")]
        E3102001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_002")]
        E3102002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_003")]
        E3102003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_004")]
        E3102004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_005")]
        E3102005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_102_006")]
        E3102006,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_104")]
        E3104,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_201")]
        E3201,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_001")]
        E3202001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_002")]
        E3202002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_003")]
        E3202003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_004")]
        E3202004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_202_005")]
        E3202005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_204")]
        E3204,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_207")]
        E3207,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_209")]
        E3209,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_301")]
        E3301,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_001")]
        E3302001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_002")]
        E3302002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_003")]
        E3302003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_004")]
        E3302004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_302_005")]
        E3302005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_304")]
        E3304,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_307")]
        E3307,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_309")]
        E3309,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_312")]
        E3312,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_001")]
        E3313001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_002")]
        E3313002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_003")]
        E3313003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_004")]
        E3313004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_313_005")]
        E3313005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_315")]
        E3315,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_581_001")]
        E3581001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_581_002")]
        E3581002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_581_003")]
        E3581003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_582")]
        E3582,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_583")]
        E3583,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_584")]
        E3584,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_001")]
        E3585001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_002")]
        E3585002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_003")]
        E3585003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_004")]
        E3585004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_005")]
        E3585005,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_006")]
        E3585006,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_007")]
        E3585007,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_008")]
        E3585008,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_009")]
        E3585009,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_010")]
        E3585010,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_011")]
        E3585011,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_012")]
        E3585012,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_013")]
        E3585013,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_014")]
        E3585014,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_015")]
        E3585015,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_585_016")]
        E3585016,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_586")]
        E3586,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_587")]
        E3587,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_588")]
        E3588,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_589")]
        E3589,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_001")]
        E3881001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_002")]
        E3881002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_003")]
        E3881003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_881_004")]
        E3881004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_001")]
        E3882001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_002")]
        E3882002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_003")]
        E3882003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_882_004")]
        E3882004,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_001")]
        E3883001,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_002")]
        E3883002,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_003")]
        E3883003,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_883_004")]
        E3883004,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_361")]
        Vat361,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_362")]
        Vat362,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_363")]
        Vat363,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_364")]
        Vat364,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_365")]
        Vat365,
        
        [System.Xml.Serialization.XmlEnumAttribute("VAT_366")]
        Vat366,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_103")]
        E3103,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_203")]
        E3203,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_303")]
        E3303,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_208")]
        E3208,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_308")]
        E3308,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_314")]
        E3314,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_106")]
        E3106,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_205")]
        E3205,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_305")]
        E3305,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_210")]
        E3210,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_310")]
        E3310,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_318")]
        E3318,
        
        [System.Xml.Serialization.XmlEnumAttribute("E3_598_002")]
        E3598002,
        
        [System.Xml.Serialization.XmlEnumAttribute("NOT_VAT_295")]
        NotVat295,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExpensesClassificationsDoc", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExpensesClassificationsDoc", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class ExpensesClassificationsDoc
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InvoiceExpensesClassificationType> _expensesInvoiceClassification;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("expensesInvoiceClassification")]
        public System.Collections.ObjectModel.Collection<InvoiceExpensesClassificationType> ExpensesInvoiceClassification
        {
            get
            {
                return _expensesInvoiceClassification;
            }
            private set
            {
                _expensesInvoiceClassification = value;
            }
        }
        
        public ExpensesClassificationsDoc()
        {
            this._expensesInvoiceClassification = new System.Collections.ObjectModel.Collection<InvoiceExpensesClassificationType>();
        }
    }
}